packages:
  - apps/*
  - packages/*
  - tooling/*
  - cli/*

catalog:
  "@tanstack/react-query": ^5.59.16
  "@trpc/client": ^11.0.0-rc.477
  "@trpc/react-query": ^11.0.0-rc.477
  "@trpc/server": ^11.0.0-rc.477
  eslint: ^9.13.0
  prettier: ^3.3.3
  tailwindcss: ^3.4.14
  typescript: ^5.6.3
  zod: ^3.23.8

catalogs:
  react18:
    react: rc
    react-dom: rc
    "@types/react": npm:types-react@rc 
    "@types/react-dom": npm:types-react-dom@rc 
