packages:
  - apps/*
  - packages/*
  - tooling/*
  - cli/*

catalog:
  "@tanstack/react-query": ^5.56.2
  "@trpc/client": ^11.0.0-rc.477
  "@trpc/react-query": ^11.0.0-rc.477
  "@trpc/server": ^11.0.0-rc.477
  eslint: ^9.11.1
  prettier: ^3.3.3
  tailwindcss: ^3.4.13
  typescript: ^5.5.4
  zod: ^3.23.8

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.9
    "@types/react-dom": ^18.3.0
